const countries = [
  { code: "AF", dialCode: "+93", flag: "🇦🇫", name: "Afghanistan" },
  { code: "AL", dialCode: "+355", flag: "🇦🇱", name: "Albania" },
  { code: "DZ", dialCode: "+213", flag: "🇩🇿", name: "Algeria" },
  { code: "AS", dialCode: "+1-684", flag: "🇦🇸", name: "American Samoa" },
  { code: "AD", dialCode: "+376", flag: "🇦🇩", name: "Andorra" },
  { code: "AO", dialCode: "+244", flag: "🇦🇴", name: "Angola" },
  { code: "AI", dialCode: "+1-264", flag: "🇦🇮", name: "Anguilla" },
  { code: "AQ", dialCode: "+672", flag: "🇦🇶", name: "Antarctica" },
  { code: "AG", dialCode: "+1-268", flag: "🇦🇬", name: "Antigua and Barbuda" },
  { code: "AR", dialCode: "+54", flag: "🇦🇷", name: "Argentina" },
  { code: "AM", dialCode: "+374", flag: "🇦🇲", name: "Armenia" },
  { code: "AW", dialCode: "+297", flag: "🇦🇼", name: "Aruba" },
  { code: "AU", dialCode: "+61", flag: "🇦🇺", name: "Australia" },
  { code: "AT", dialCode: "+43", flag: "🇦🇹", name: "Austria" },
  { code: "AZ", dialCode: "+994", flag: "🇦🇿", name: "Azerbaijan" },
  { code: "BS", dialCode: "+1-242", flag: "🇧🇸", name: "Bahamas" },
  { code: "BH", dialCode: "+973", flag: "🇧🇭", name: "Bahrain" },
  { code: "BD", dialCode: "+880", flag: "🇧🇩", name: "Bangladesh" },
  { code: "BB", dialCode: "+1-246", flag: "🇧🇧", name: "Barbados" },
  { code: "BY", dialCode: "+375", flag: "🇧🇾", name: "Belarus" },
  { code: "BE", dialCode: "+32", flag: "🇧🇪", name: "Belgium" },
  { code: "BZ", dialCode: "+501", flag: "🇧🇿", name: "Belize" },
  { code: "BJ", dialCode: "+229", flag: "🇧🇯", name: "Benin" },
  { code: "BM", dialCode: "+1-441", flag: "🇧🇲", name: "Bermuda" },
  { code: "BT", dialCode: "+975", flag: "🇧🇹", name: "Bhutan" },
  { code: "BO", dialCode: "+591", flag: "🇧🇴", name: "Bolivia" },
  { code: "BQ", dialCode: "+599", flag: "🇧🇶", name: "Bonaire, Sint Eustatius and Saba" },
  { code: "BA", dialCode: "+387", flag: "🇧🇦", name: "Bosnia and Herzegovina" },
  { code: "BW", dialCode: "+267", flag: "🇧🇼", name: "Botswana" },
  { code: "BV", dialCode: "+47", flag: "🇧🇻", name: "Bouvet Island" },
  { code: "BR", dialCode: "+55", flag: "🇧🇷", name: "Brazil" },
  { code: "IO", dialCode: "+246", flag: "🇮🇴", name: "British Indian Ocean Territory" },
  { code: "BN", dialCode: "+673", flag: "🇧🇳", name: "Brunei Darussalam" },
  { code: "BG", dialCode: "+359", flag: "🇧🇬", name: "Bulgaria" },
  { code: "BF", dialCode: "+226", flag: "🇧🇫", name: "Burkina Faso" },
  { code: "BI", dialCode: "+257", flag: "🇧🇮", name: "Burundi" },
  { code: "CV", dialCode: "+238", flag: "🇨🇻", name: "Cabo Verde" },
  { code: "KH", dialCode: "+855", flag: "🇰🇭", name: "Cambodia" },
  { code: "CM", dialCode: "+237", flag: "🇨🇲", name: "Cameroon" },
  { code: "CA", dialCode: "+1", flag: "🇨🇦", name: "Canada" },
  { code: "KY", dialCode: "+1-345", flag: "🇰🇾", name: "Cayman Islands" },
  { code: "CF", dialCode: "+236", flag: "🇨🇫", name: "Central African Republic" },
  { code: "TD", dialCode: "+235", flag: "🇹🇩", name: "Chad" },
  { code: "CL", dialCode: "+56", flag: "🇨🇱", name: "Chile" },
  { code: "CN", dialCode: "+86", flag: "🇨🇳", name: "China" },
  { code: "CX", dialCode: "+61", flag: "🇨🇽", name: "Christmas Island" },
  { code: "CC", dialCode: "+61", flag: "🇨🇨", name: "Cocos (Keeling) Islands" },
  { code: "CO", dialCode: "+57", flag: "🇨🇴", name: "Colombia" },
  { code: "KM", dialCode: "+269", flag: "🇰🇲", name: "Comoros" },
  { code: "CG", dialCode: "+242", flag: "🇨🇬", name: "Congo" },
  { code: "CD", dialCode: "+243", flag: "🇨🇩", name: "Congo (DRC)" },
  { code: "CK", dialCode: "+682", flag: "🇨🇰", name: "Cook Islands" },
  { code: "CR", dialCode: "+506", flag: "🇨🇷", name: "Costa Rica" },
  { code: "CI", dialCode: "+225", flag: "🇨🇮", name: "Côte d’Ivoire" },
  { code: "HR", dialCode: "+385", flag: "🇭🇷", name: "Croatia" },
  { code: "CU", dialCode: "+53", flag: "🇨🇺", name: "Cuba" },
  { code: "CW", dialCode: "+599", flag: "🇨🇼", name: "Curaçao" },
  { code: "CY", dialCode: "+357", flag: "🇨🇾", name: "Cyprus" },
  { code: "CZ", dialCode: "+420", flag: "🇨🇿", name: "Czechia" },
  { code: "DK", dialCode: "+45", flag: "🇩🇰", name: "Denmark" },
  { code: "DJ", dialCode: "+253", flag: "🇩🇯", name: "Djibouti" },
  { code: "DM", dialCode: "+1-767", flag: "🇩🇲", name: "Dominica" },
  { code: "DO", dialCode: "+1-809", flag: "🇩🇴", name: "Dominican Republic" },
  { code: "EC", dialCode: "+593", flag: "🇪🇨", name: "Ecuador" },
  { code: "EG", dialCode: "+20", flag: "🇪🇬", name: "Egypt" },
  { code: "SV", dialCode: "+503", flag: "🇸🇻", name: "El Salvador" },
  { code: "GQ", dialCode: "+240", flag: "🇬🇶", name: "Equatorial Guinea" },
  { code: "ER", dialCode: "+291", flag: "🇪🇷", name: "Eritrea" },
  { code: "EE", dialCode: "+372", flag: "🇪🇪", name: "Estonia" },
  { code: "SZ", dialCode: "+268", flag: "🇸🇿", name: "Eswatini" },
  { code: "ET", dialCode: "+251", flag: "🇪🇹", name: "Ethiopia" },
  { code: "FK", dialCode: "+500", flag: "🇫🇰", name: "Falkland Islands" },
  { code: "FO", dialCode: "+298", flag: "🇫🇴", name: "Faroe Islands" },
  { code: "FJ", dialCode: "+679", flag: "🇫🇯", name: "Fiji" },
  { code: "FI", dialCode: "+358", flag: "🇫🇮", name: "Finland" },
  { code: "FR", dialCode: "+33", flag: "🇫🇷", name: "France" },
  { code: "GF", dialCode: "+594", flag: "🇬🇫", name: "French Guiana" },
  { code: "PF", dialCode: "+689", flag: "🇵🇫", name: "French Polynesia" },
  { code: "TF", dialCode: "+262", flag: "🇹🇫", name: "French Southern Territories" },
  { code: "GA", dialCode: "+241", flag: "🇬🇦", name: "Gabon" },
  { code: "GM", dialCode: "+220", flag: "🇬🇲", name: "Gambia" },
  { code: "GE", dialCode: "+995", flag: "🇬🇪", name: "Georgia" },
  { code: "DE", dialCode: "+49", flag: "🇩🇪", name: "Germany" },
  { code: "GH", dialCode: "+233", flag: "🇬🇭", name: "Ghana" },
  { code: "GI", dialCode: "+350", flag: "🇬🇮", name: "Gibraltar" },
  { code: "GR", dialCode: "+30", flag: "🇬🇷", name: "Greece" },
  { code: "GL", dialCode: "+299", flag: "🇬🇱", name: "Greenland" },
  { code: "GD", dialCode: "+1-473", flag: "🇬🇩", name: "Grenada" },
  { code: "GP", dialCode: "+590", flag: "🇬🇵", name: "Guadeloupe" },
  { code: "GU", dialCode: "+1-671", flag: "🇬🇺", name: "Guam" },
  { code: "GT", dialCode: "+502", flag: "🇬🇹", name: "Guatemala" },
  { code: "GG", dialCode: "+44-1481", flag: "🇬🇬", name: "Guernsey" },
  { code: "GN", dialCode: "+224", flag: "🇬🇳", name: "Guinea" },
  { code: "GW", dialCode: "+245", flag: "🇬🇼", name: "Guinea-Bissau" },
  { code: "GY", dialCode: "+592", flag: "🇬🇾", name: "Guyana" },
  { code: "HT", dialCode: "+509", flag: "🇭🇹", name: "Haiti" },
  { code: "HM", dialCode: "+672", flag: "🇭🇲", name: "Heard Island and McDonald Islands" },
  { code: "VA", dialCode: "+379", flag: "🇻🇦", name: "Holy See" },
  { code: "HN", dialCode: "+504", flag: "🇭🇳", name: "Honduras" },
  { code: "HK", dialCode: "+852", flag: "🇭🇰", name: "Hong Kong" },
  { code: "HU", dialCode: "+36", flag: "🇭🇺", name: "Hungary" },
  { code: "IS", dialCode: "+354", flag: "🇮🇸", name: "Iceland" },
  { code: "IN", dialCode: "+91", flag: "🇮🇳", name: "India" },
  { code: "ID", dialCode: "+62", flag: "🇮🇩", name: "Indonesia" },
  { code: "IR", dialCode: "+98", flag: "🇮🇷", name: "Iran" },
  { code: "IQ", dialCode: "+964", flag: "🇮🇶", name: "Iraq" },
  { code: "IE", dialCode: "+353", flag: "🇮🇪", name: "Ireland" },
  { code: "IM", dialCode: "+44-1624", flag: "🇮🇲", name: "Isle of Man" },
  { code: "IL", dialCode: "+972", flag: "🇮🇱", name: "Israel" },
  { code: "IT", dialCode: "+39", flag: "🇮🇹", name: "Italy" },
  { code: "JM", dialCode: "+1-876", flag: "🇯🇲", name: "Jamaica" },
  { code: "JP", dialCode: "+81", flag: "🇯🇵", name: "Japan" },
  { code: "JE", dialCode: "+44-1534", flag: "🇯🇪", name: "Jersey" },
  { code: "JO", dialCode: "+962", flag: "🇯🇴", name: "Jordan" },
  { code: "KZ", dialCode: "+7", flag: "🇰🇿", name: "Kazakhstan" },
  { code: "KE", dialCode: "+254", flag: "🇰🇪", name: "Kenya" },
  { code: "KI", dialCode: "+686", flag: "🇰🇮", name: "Kiribati" },
  { code: "KP", dialCode: "+850", flag: "🇰🇵", name: "North Korea" },
  { code: "KR", dialCode: "+82", flag: "🇰🇷", name: "South Korea" },
  { code: "KW", dialCode: "+965", flag: "🇰🇼", name: "Kuwait" },
  { code: "KG", dialCode: "+996", flag: "🇰🇬", name: "Kyrgyzstan" },
  { code: "LA", dialCode: "+856", flag: "🇱🇦", name: "Laos" },
  { code: "LV", dialCode: "+371", flag: "🇱🇻", name: "Latvia" },
  { code: "LB", dialCode: "+961", flag: "🇱🇧", name: "Lebanon" },
  { code: "LS", dialCode: "+266", flag: "🇱🇸", name: "Lesotho" },
  { code: "LR", dialCode: "+231", flag: "🇱🇷", name: "Liberia" },
  { code: "LY", dialCode: "+218", flag: "🇱🇾", name: "Libya" },
  { code: "LI", dialCode: "+423", flag: "🇱🇮", name: "Liechtenstein" },
  { code: "LT", dialCode: "+370", flag: "🇱🇹", name: "Lithuania" },
  { code: "LU", dialCode: "+352", flag: "🇱🇺", name: "Luxembourg" },
  { code: "MO", dialCode: "+853", flag: "🇲🇴", name: "Macao" },
  { code: "MG", dialCode: "+261", flag: "🇲🇬", name: "Madagascar" },
  { code: "MW", dialCode: "+265", flag: "🇲🇼", name: "Malawi" },

  { code: "MY", dialCode: "+60", flag: "🇲🇾", name: "Malaysia" },
  { code: "MV", dialCode: "+960", flag: "🇲🇻", name: "Maldives" },
  { code: "ML", dialCode: "+223", flag: "🇲🇱", name: "Mali" },
  { code: "MT", dialCode: "+356", flag: "🇲🇹", name: "Malta" },
  { code: "MH", dialCode: "+692", flag: "🇲🇭", name: "Marshall Islands" },
  { code: "MQ", dialCode: "+596", flag: "🇲🇶", name: "Martinique" },
  { code: "MR", dialCode: "+222", flag: "🇲🇷", name: "Mauritania" },
  { code: "MU", dialCode: "+230", flag: "🇲🇺", name: "Mauritius" },
  { code: "YT", dialCode: "+262", flag: "🇾🇹", name: "Mayotte" },
  { code: "MX", dialCode: "+52", flag: "🇲🇽", name: "Mexico" },
  { code: "FM", dialCode: "+691", flag: "🇫🇲", name: "Micronesia" },
  { code: "MD", dialCode: "+373", flag: "🇲🇩", name: "Moldova" },
  { code: "MC", dialCode: "+377", flag: "🇲🇨", name: "Monaco" },
  { code: "MN", dialCode: "+976", flag: "🇲🇳", name: "Mongolia" },
  { code: "ME", dialCode: "+382", flag: "🇲🇪", name: "Montenegro" },
  { code: "MS", dialCode: "+1-664", flag: "🇲🇸", name: "Montserrat" },
  { code: "MA", dialCode: "+212", flag: "🇲🇦", name: "Morocco" },
  { code: "MZ", dialCode: "+258", flag: "🇲🇿", name: "Mozambique" },
  { code: "MM", dialCode: "+95", flag: "🇲🇲", name: "Myanmar (Burma)" },
  { code: "NA", dialCode: "+264", flag: "🇳🇦", name: "Namibia" },
  { code: "NR", dialCode: "+674", flag: "🇳🇷", name: "Nauru" },
  { code: "NP", dialCode: "+977", flag: "🇳🇵", name: "Nepal" },
  { code: "NL", dialCode: "+31", flag: "🇳🇱", name: "Netherlands" },
  { code: "NC", dialCode: "+687", flag: "🇳🇨", name: "New Caledonia" },
  { code: "NZ", dialCode: "+64", flag: "🇳🇿", name: "New Zealand" },
  { code: "NI", dialCode: "+505", flag: "🇳🇮", name: "Nicaragua" },
  { code: "NE", dialCode: "+227", flag: "🇳🇪", name: "Niger" },
  { code: "NG", dialCode: "+234", flag: "🇳🇬", name: "Nigeria" },
  { code: "NU", dialCode: "+683", flag: "🇳🇺", name: "Niue" },
  { code: "NF", dialCode: "+672", flag: "🇳🇫", name: "Norfolk Island" },
  { code: "MK", dialCode: "+389", flag: "🇲🇰", name: "North Macedonia" },
  { code: "MP", dialCode: "+1-670", flag: "🇲🇵", name: "Northern Mariana Islands" },
  { code: "NO", dialCode: "+47", flag: "🇳🇴", name: "Norway" },
  { code: "OM", dialCode: "+968", flag: "🇴🇲", name: "Oman" },
];

export default countries;
